sudo: required
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
before_install:
  - sudo apt-get install fuse
  - sudo chmod a+r /etc/fuse.conf
install:
  - pip install -r tests/requirements.txt
script:
  - coverage run --source ./ --omit ./tests/server.py -m unittest tests
after_success:
  - coveralls
